#!/usr/bin/env bash

# convert-video-to-mp4          Copyright (C) 2016 Jonas Sjöberg
# ~~~~~~~~~~~~~~~~~~~~          https://github.com/jonasjberg
#
# Convert videos to mp4 using ffmpeg, motivated by reducing disk space.
# Especially screen capture recordings in ogv- and webm-formats seem
# to take up more space than necessary in my usage. This solves that.

set -e

# This esentially determines the final output format.
NEW_EXT="mp4"

function die()
{
    FORMAT="[ERROR] %s \"%s\" ..\n"
    printf "$FORMAT" "$1" "$2"
    exit 1
}


arg=${1:-}
[ -z "$arg" ] && die "Got null argument" "${arg}"
[ -e "$arg" ] || die "Does not exist"    "${arg}"
[ -d "$arg" ] && die "Is a directory"    "${arg}"
[ -f "$arg" ] || die "Not a file"        "${arg}"

orig="$arg"
orig_no_ext="${arg%.*}"
output="${orig_no_ext}.${NEW_EXT}"
printf '%-25s : "%s"\n' "converting from source" "${orig}"
printf '%-25s : "%s"\n' "to destination"         "${output}"

# Information on ffmpeg command options used:
# http://askubuntu.com/questions/12182/how-can-i-convert-an-ogv-file-to-mp4
# http://askubuntu.com/a/470475
ffmpeg -i "$orig" -c:v libx264 -preset veryslow -crf 22 -c:a libmp3lame -qscale:a 2 -ac 2 -ar 44100 -- "$output"

