#!/usr/bin/env bash

# exiftooldate          Written in 2016 by Jonas Sjöberg
# ~~~~~~~~~~~~          https://github.com/jonasjberg
#
# Get date/time-information from file(s) using exiftool.
# Obviously requires exiftool to be installed.


if ! command -v "exiftool" >/dev/null 2>&1
then
    printf "This script requires \"exiftool\" to run.\n"
    exit 127
fi

if [ $# -eq 0 ]
then
    printf "Usage: $(basename $0) [FILE]..\n"
    exit 1
fi

for arg in "$@"
do
    printf "\n\n%s\n" "$arg"
    exiftool -short -e -a -s -G1 "-*date*" "$arg" \
    | awk '{printf "%-15.15s %20.20s %-s %-s %s\n", $1, $2, $3, $4, $5}'
done

exit $?

