#!/bin/bash
#   ______________________________________________________________________
#
#   PULL-FROM  --  dead simple rsync wrapper
#   written by Jonas Sjöberg for *personal* use.
#                                                 Last updated: 2015-05-16
#   ______________________________________________________________________

#   'pull-from' is a simple wrapper-script for rsync.
#   It's useful for synchronizing a local directory with a remote via SSH.
#   Please note that what I call 'synchronizing' here is a copy and *DELETE*.
#   That is, any files present in the local directory will be deleted if not
#   present in the corresponding remote directory.  Basically, it's a hard
#   reset, I.E., "pull" .. SO BE CAREFUL! Use the --dry-run switch first!


# MANDATORY USER CONFIGURATION
# Source hostname or IP-adress and full source path. Set these first.
SOURCE_HOST="127.0.0.1"
SOURCE_PATH="~/test"

# Rsync options used.
FLAGS="-avhPi --stats --delete --exclude="${0##*/}""
#       ^^^^^   ^___^   ^____^   ^_______________^
#       |||||     |       |        |
#       |||||     |       |        +--- exclude this script
#       |||||     |       +------------ delete extraneous files from dest
#       |||||     +-------------------- print verbose statistics
#       ||||+-------------------------- request list of changes to files
#       |||+--------------------------- same as --partial --progress
#       ||+---------------------------- numbers in human-readable format
#       |+----------------------------- verbosity as in more information
#       +------------------------------ archive mode, equivalent to -rlptgoD

# Trial run enable/disable.
DRY="--dry-run"
unset DRY
# NOTE: Uncomment the above line to do a live run.
#       First do a trial run to make sure everything is in order.
#       --dry-run is for testing without actually making any changes to files.

# ------------------------------------------------------------------------------

# Get the full directory path to this script location.
THIS_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# Run this here compound command.
COMMAND="rsync ${FLAGS} "${USER}@${SOURCE_HOST}:"${SOURCE_PATH}"" "${THIS_DIR}" ${DRY}"

# OK! lets go ..
echo "[*] Command to execute: $COMMAND .."
read -rsp $'Press any key to continue...\n' -n 1 key
$COMMAND

echo "[*] Done .."
exit 0
