#!/usr/bin/env bash

# pdflatex wrapper
# ----------------
# Script for converting LaTeX source files to pdf using pdflatex.
# Written in 2014 by Jonas Sjöberg for PRIVATE USE.
# Updated 2015-06-16.

INPUT="${1}"
OUTPUT="../build"

# check that pdflatex is available
if ! command -v "pdflatex" >/dev/null;
then
    echo "Can not execute pdflatex! Is it installed? Is it in your \$PATH?"
    exit 127                          # exit code 127:  "command not found"
fi


if [[ "${INPUT}" && "${INPUT-x}" ]];
then

    mkdir -pv ${OUTPUT}

    echo "Running pdflatex .."

    pdflatex -synctex=1 -interaction=nonstopmode -shell-escape \
    --output-directory="${OUTPUT}" "${INPUT}"

    echo ".. Done running pdflatex!"
    exit $?

else
    echo "Compile WHAT?" 1>&2
    echo "Usage: $0 <texsourcefile.tex>" 1>&2

    exit 1
fi
