#!/bin/bash
# Generate previews of vrml 3D models using view3dscene.
# Outputs png images for six angles per 3D-model.
# first written by Jonas Sjöberg in April 2015.
# Updated June 2015.


set -e

# abort if we can not execute view3dscene
if ! command -v "view3dscene" >/dev/null; then
    echo "Can not execute view3dscene! Is it installed? Is it in your \$PATH?" 1>&2
    echo "Aborting .."
    exit 127
fi


COUNTER_VRMLFILES=0
COUNTER_TOTALPNGS=0

echo "Generating previews of 3D-models .."
echo ""

for vrmlfile in *.wrl;
do                                               # iterate through files
    echo "processing vrmlfile: "$vrmlfile" .."

    COUNTER_VRMLFILES=$[$COUNTER_VRMLFILES +1]

    for angle in {0..6};
    do                                           # iterate through angles per file
        outputfile="${vrmlfile%.*}_${angle}.png" # (%.* strips file extension)
                                                 
        if [ ! -f $outputfile ];                 # make sure file does not exist
        then                                     # ok the file isn't there
            echo "writing: "$outputfile" .."
            view3dscene "${vrmlfile}" --viewpoint "$angle" \
                        --screenshot 0 "${outputfile}";

            COUNTER_TOTALPNGS=$[$COUNTER_TOTALPNGS +1]
        else                                     # file already exists
            echo "error: "$outputfile" already exists! skipping .."
        fi
    done                                         # angle iteration done

    echo ""
done                                             # file iteration done


echo "Done generating previews of 3D-models!"
echo "Total number of vrmlfiles processed (including skipped): $COUNTER_VRMLFILES"
echo "Total number of png images generated: $COUNTER_TOTALPNGS"

exit $?                                          # exit with last process exit status

